controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

liste_groupes_musicaux:
    path: /groupes-musicaux
    controller: App\Controller\GroupeMusicalController::listeGroupesMusicaux
    methods: [GET]

supprimer_groupe_musical:
    path: /groupes-musicaux/{id}
    controller: App\Controller\GroupeMusicalController::supprimerGroupeMusical
    methods: [DELETE]

groupe_musical_upload:
    path: '/groupes-musicaux/upload-excel'
    controller: App\Controller\GroupeMusicalController::uploadExcel
    methods: ['POST']

actualizeaza_nume_groupe_musical:
    path: '/groupes-musicaux/{id}'
    controller: App\Controller\GroupeMusicalController::actualizeazaNumeGroupeMusical
    methods: ['PUT']